/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateSelectedMenuArgs } from "./CreateSelectedMenuArgs";
import { UpdateSelectedMenuArgs } from "./UpdateSelectedMenuArgs";
import { DeleteSelectedMenuArgs } from "./DeleteSelectedMenuArgs";
import { SelectedMenuFindManyArgs } from "./SelectedMenuFindManyArgs";
import { SelectedMenuFindUniqueArgs } from "./SelectedMenuFindUniqueArgs";
import { SelectedMenu } from "./SelectedMenu";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { SelectedMenuService } from "../selectedMenu.service";

@graphql.Resolver(() => SelectedMenu)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class SelectedMenuResolverBase {
  constructor(
    protected readonly service: SelectedMenuService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "SelectedMenu",
    action: "read",
    possession: "any",
  })
  async _selectedMenusMeta(
    @graphql.Args() args: SelectedMenuFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [SelectedMenu])
  @nestAccessControl.UseRoles({
    resource: "SelectedMenu",
    action: "read",
    possession: "any",
  })
  async selectedMenus(
    @graphql.Args() args: SelectedMenuFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SelectedMenu[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "SelectedMenu",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => SelectedMenu, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SelectedMenu",
    action: "read",
    possession: "own",
  })
  async selectedMenu(
    @graphql.Args() args: SelectedMenuFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SelectedMenu | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "SelectedMenu",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => SelectedMenu)
  @nestAccessControl.UseRoles({
    resource: "SelectedMenu",
    action: "create",
    possession: "any",
  })
  async createSelectedMenu(
    @graphql.Args() args: CreateSelectedMenuArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SelectedMenu> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "SelectedMenu",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"SelectedMenu"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => SelectedMenu)
  @nestAccessControl.UseRoles({
    resource: "SelectedMenu",
    action: "update",
    possession: "any",
  })
  async updateSelectedMenu(
    @graphql.Args() args: UpdateSelectedMenuArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<SelectedMenu | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "SelectedMenu",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"SelectedMenu"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SelectedMenu)
  @nestAccessControl.UseRoles({
    resource: "SelectedMenu",
    action: "delete",
    possession: "any",
  })
  async deleteSelectedMenu(
    @graphql.Args() args: DeleteSelectedMenuArgs
  ): Promise<SelectedMenu | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [User])
  @nestAccessControl.UseRoles({
    resource: "SelectedMenu",
    action: "read",
    possession: "any",
  })
  async users(
    @graphql.Parent() parent: SelectedMenu,
    @graphql.Args() args: UserFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const results = await this.service.findUsers(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }
}
